"""initial_schema

Revision ID: 601a13a099ad
Revises: 
Create Date: 2026-06-24 03:25:01.986101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '601a13a099ad'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concept_set',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('concept_set_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('domain_id', sa.String(length=50), nullable=True),
    sa.Column('project_id', sa.String(length=255), nullable=True),
    sa.Column('doi', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('concept_set_name')
    )
    op.create_table('concept_set_version',
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('concept_set_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=True),
    sa.Column('version_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('parent_version_id', sa.Integer(), nullable=True),
    sa.Column('ohdsi_expression', sa.JSON(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('scope_notes', sa.Text(), nullable=True),
    sa.Column('author_name', sa.String(length=255), nullable=True),
    sa.Column('research_study_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['concept_set_id'], ['concept_set.id'], ),
    sa.ForeignKeyConstraint(['parent_version_id'], ['concept_set_version.version_id'], ),
    sa.PrimaryKeyConstraint('version_id')
    )
    op.create_table('concept_set_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('concept_name', sa.String(length=255), nullable=True),
    sa.Column('domain_id', sa.String(length=20), nullable=True),
    sa.Column('vocabulary_id', sa.String(length=20), nullable=True),
    sa.Column('concept_class_id', sa.String(length=20), nullable=True),
    sa.Column('standard_concept', sa.String(length=1), nullable=True),
    sa.Column('concept_code', sa.String(length=50), nullable=True),
    sa.Column('valid_start_date', sa.Date(), nullable=True),
    sa.Column('valid_end_date', sa.Date(), nullable=True),
    sa.Column('invalid_reason', sa.String(length=1), nullable=True),
    sa.Column('is_excluded', sa.Boolean(), nullable=False),
    sa.Column('include_descendants', sa.Boolean(), nullable=False),
    sa.Column('include_mapped', sa.Boolean(), nullable=False),
    sa.Column('descendant_count', sa.Integer(), nullable=True),
    sa.Column('review_status', sa.String(length=50), nullable=True),
    sa.Column('review_comment', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['concept_set_version.version_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviewer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('decision', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['concept_set_version.version_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviewer')
    op.drop_table('concept_set_member')
    op.drop_table('concept_set_version')
    op.drop_table('concept_set')
    # ### end Alembic commands ###
